### ISSUE TITLE
VariablesSnapshotListener - Can't save a snapshot of the process variables

### ISSUE THREAD

**Issue by everimbaq** [walmartlabs/concord#10]
An error "Save snapshot failed" happens before my flow finish.  DeployAppInfo is a java class defined in my plugin.

The parent process report an error like below.
![image](https://user-images.githubusercontent.com/7394813/61454245-ef806800-a992-11e9-9280-1e76db1aea9c.png)

The child process report an error like below.
![image](https://user-images.githubusercontent.com/7394813/61453761-95cb6e00-a991-11e9-9da1-46ccb6b79d79.png)

**Comment by ibodrov** [comment]
`DeployAppInfo` must implement `java.io.Serializable`
Using custom classes for flow variables can also be problematic in some other situations - e.g. when working with forms. Check out the last paragraph here https://concord.walmartlabs.com/docs/getting-started/tasks.html#task-output-and-error-handling

**Comment by everimbaq** [comment]
solved my problem.
