### ISSUE TITLE
Can i optimize memory usage of agent?

### ISSUE THREAD

**Issue by everimbaq** [walmartlabs/concord#14]
After a concurrent test and learning the source code, i found that one workflow instance  would take 128M memory and create a JVM process.

Considering we have ten thousands of projects to build everyday,  and one workflow may last 10 minutes or more（doing some performance test）,  we need 50~100G of memory. I think walmart will need much more.

I'd like to know is that expected, or is there any method to optimize resource usage?

**Comment by ibodrov** [comment]
You can experiment with setting `-Xmx` lower, but anything lower than 64m is not realistic, I think.
Build tools are memory hungry too.

**Comment by ibodrov** [comment]
There's also a K8s operator for Agents https://github.com/walmartlabs/concord/tree/master/k8s/agent-operator
With autoscaling (pretty simplistic, but working) and graceful shutdown/upgrades.
Can be used to improve off-peak resource usage if running on K8s.

**Comment by everimbaq** [comment]
> There's also a K8s operator for Agents https://github.com/walmartlabs/concord/tree/master/k8s/agent-operator
> With autoscaling (pretty simplistic, but working) and graceful shutdown/upgrades.
> Can be used to improve off-peak resource usage if running on K8s.
Yeah, We are considering to use K8s to autoscale based on memory usage, thanks.
