### ISSUE TITLE
Is a jvm process started per pipeline or request?

### ISSUE THREAD

**Issue by everimbaq** [walmartlabs/concord#15]
After a performance test with  1 CPU and 2GB RAM  agent and server per pod,  we found the server can handle 100 request per second. But the requests are async queued and the real execution of workflow takes seconds. Therefore the system can only execute and finish 500 tasks one hour( a simple print helloworld task). I think its a little slow for us ( or my configuration setting is wrong?).

I'm trying to find some ways to optimize the speed. Before that, i'd like to make sure is a jvm process started per request? As i know, preparing and start a jvm process takes seconds of time, for what sake is this design made. If i set one jvm and one repo to execute multi pipeline at the same time, is that feasible？

Thanks a lot.

**Comment by ibodrov** [comment]
It's a JVM per process execution.
You can control how many parallel processes one agent can run with [configuration](https://github.com/walmartlabs/concord/blob/master/agent/src/main/resources/concord-agent.conf#L28-L30)

The agent also tries to [cache](https://github.com/walmartlabs/concord/blob/master/agent/src/main/resources/concord-agent.conf#L38-L44) "pre-forked" JVMs with the same dependencies to reduce the JVM startup/warmup costs.

Our production setup consists of several Server instances (in an load-balancing/HA configuration) and 100s of Agents.

**Comment by everimbaq** [comment]
> It's a JVM per process execution.
> You can control how many parallel processes one agent can run with [configuration](https://github.com/walmartlabs/concord/blob/master/agent/src/main/resources/concord-agent.conf#L28-L30)
> 
> The agent also tries to [cache](https://github.com/walmartlabs/concord/blob/master/agent/src/main/resources/concord-agent.conf#L38-L44) "pre-forked" JVMs with the same dependencies to reduce the JVM startup/warmup costs.
> 
> Our production setup consists of several Server instances (in an load-balancing/HA configuration) and 100s of Agents.

Yes, Jvm cache is really good design. Our pipeline includes steps like building, unit test , auto test and performance test, all  takes lots of time.Maybe i should make pipeline tasks parallel in one jvm. 

I set 6 workers per agent (6*128M + 256M  = 1G). Is your agents 1C1G or any recommendation?

**Comment by ibodrov** [comment]
Agents themselves produce very little GC pressure.
The walmartlabs/concord-agent Docker image uses the default GC for JVM 8, which is `Parallel GC` AFAIR.

**Comment by everimbaq** [comment]
> Agents themselves produce very little GC pressure.
> The walmartlabs/concord-agent Docker image uses the default GC for JVM 8, which is `Parallel GC` AFAIR.

Sorry for my ambiguous words.  Currently my agent is using 1core 1G ram per pod . I'd like to know is your agents 1core 1G ram,  or any other resource specification recommended? Thanks again.

**Comment by ibodrov** [comment]
We use a mix and match of agents. Those that are running on k8s are typically in 2 cpu / 2 GB RAM pods. We also use agents on "regular" VMs up to 200GB RAM for large-scale Ansible deployments.

**Comment by everimbaq** [comment]
Thank you so much for your generous help.
