### ISSUE TITLE
Kerberos auth is broken in nested containers.

### ISSUE THREAD

**Issue by mtkunkel** [walmartlabs/concord#160]
Kinit occurs in the parent container:
```
16:00:20 [INFO ] TGT obtained, expired at 'Thu Oct 01 07:00:20 UTC 2020'
16:00:20 [INFO ] TGT renew at Thu Oct 01 06:59:20 UTC 2020
16:00:21 ANSIBLE: latest: Pulling from walmartlabs/concord-ansible/ansible-docker-pymssql-pyodbc
16:00:21 ANSIBLE: 3c72a8ed6814: Pulling fs layer
16:00:21 ANSIBLE: 46bc21ec4861: Pulling fs layer
16:00:21 ANSIBLE: 3b889782b0ff: Pulling fs layer
```

`KRB5CCNAME` gets dropped in a directory not available in the child container: https://github.com/walmartlabs/concord/blob/master/plugins/tasks/ansible/src/main/java/com/walmartlabs/concord/plugins/ansible/KerberosAuth.java#L70

`No Kerberos credentials available (default cache: /tmp/concord/prefork6456798604649317788/payload/.concord_tmp/ansible4533715454010284806/tgt-ticket) `

Should the krb5 ticket cache be located in `workdir` like Private Keys (with similar cleanup)?
Should we just mount through the `tempDir` to the child?  Potentially to a different location and re-set `KRB5CCNAME`?

**Comment by ibodrov** [comment]
> Should the krb5 ticket cache be located in workdir like Private Keys (with similar cleanup)?
`/tmp/concord/prefork6456798604649317788/payload` is a path in workDir.

So `/tmp/concord/prefork6456798604649317788/payload/.concord_tmp/ansible4533715454010284806/tgt-ticket` _should_ be available as `/workspace/.concord_tmp/ansible4533715454010284806/tgt-ticket`.

Two potential solutions from the top of my head:
- we can mount the original path in addition to `/workspace`. The directory is available for DIND containers anyway;
- we can make [KerberosAuth](https://github.com/walmartlabs/concord/blob/master/plugins/tasks/ansible/src/main/java/com/walmartlabs/concord/plugins/ansible/KerberosAuth.java#L70) "DIND-aware" by replacing `workDir` in `tgtCacheFile.toString()` with `/workspace` if it `dockerImage` is specified.

Unfortunately, I don't have an easy way to test it locally. Is there a "Kerberos-in-a-box" kinda thing?

**Comment by amithkb** [comment]
https://github.com/walmartlabs/concord/pull/167 

before - 

![image](https://user-images.githubusercontent.com/70886332/95345589-8444ed80-08d8-11eb-8fcc-b0554249e634.png)


after - 

![image](https://user-images.githubusercontent.com/70886332/95345624-8eff8280-08d8-11eb-988f-142254ba4b80.png)
