### ISSUE TITLE
Concord-v2 runtime: custom form value injection not working as intended

### ISSUE THREAD

**Issue by codyaverett** [walmartlabs/concord#217]
Arbitrary values are not parsed and made available in a custom form values property.  
Thus I had to work around and smuggle my object in a form value directly then parse the JSON value from a string.

e.g. 
Dynamic form definition
![image](https://user-images.githubusercontent.com/3270702/98394081-d97f3680-201f-11eb-9aa9-076b0b743b4d.png)

data.js received
![image](https://user-images.githubusercontent.com/3270702/98394101-e00dae00-201f-11eb-9d89-83ab1445fd93.png)

**Comment by ibodrov** [comment]
Fixed by https://github.com/walmartlabs/concord/pull/219

**Comment by codyaverett** [comment]
Just saw this fix.  Thank you Yury! @brig 🍺
