### ISSUE TITLE
bug: inventory api create query consumes wrong content-type

### ISSUE THREAD

**Issue by justenwalker** [walmartlabs/concord#26]
[Code](https://github.com/walmartlabs/concord/blob/0be1356cee4a193fb5b638dc27753afe4b4b85d5/server/impl/src/main/java/com/walmartlabs/concord/server/org/inventory/InventoryQueryResource.java#L96): 
```java
@Consumes(MediaType.APPLICATION_JSON)
```

[Documentation](http://concord.walmart.com/docs/api/inventory/inventory-query.html#create-update-inventory-query):

> Headers Authorization, Content-Type: text/plain

Results in getting a 415 error when setting the content type to `text/plain` as documented.
If you set the content-type header to application/json it works; even though the content provided is a SQL query and not valid JSON.

Seems this was a regression during change-over to [JSONStore](https://github.com/walmartlabs/concord/commit/0be1356cee4a193fb5b638dc27753afe4b4b85d5)

**Comment by ibodrov** [comment]
The inventory API is deprecated and left in the tree for backward compatibility.
We decided not to fix anything there as it might be a breaking change - even if the header's value doesn't make much sense. Its replacement, the JSON Store API, uses JSON bodies in the query creation endpoint.

We will update the documentation accordingly.

**Comment by ibodrov** [comment]
This takes care of the API's side of things
https://github.com/walmartlabs/concord/commit/569fe929ff97d8fa4dced895f8d57b4d50356487

The docs PR is pending internal review.

**Comment by ibodrov** [comment]
The [docs](https://github.com/walmartlabs/concord-website/commit/be333feecb9a3266e13b002a5416d0973b3039a3).

The fix was released in 1.53.0.
