### ISSUE TITLE
Invalid SSL Certificate for concord.walmartlabs.com

### ISSUE THREAD

**Issue by nextrevision** [walmartlabs/concord#261]
When trying to reach the project homepage (concord.walmartlabs.com) an `Invalid SSL Certificate` error is thrown.

**Comment by mtkunkel** [comment]
@cwstege ^^^ ?

**Comment by mtkunkel** [comment]
We are aware of it, unsure why the external cert renewal isn't automated. The website can be run local from: https://github.com/walmartlabs/concord-website  

 Looking into github pages as a backup.

**Comment by mtkunkel** [comment]
A WIP (mostly working) port of the website is now avail via GH pages: https://walmartlabs.github.io/concord-website/

**Comment by ibodrov** [comment]
I believe this is fixed now.
