### ISSUE TITLE
Failed Dependency transfer merely logs

### ISSUE THREAD

**Issue by Randgalt** [walmartlabs/concord#27]
When a dependency transfer fails the system merely logs it. It should also post some kind of event or other notice so that downstream plugins can take action. 

https://github.com/walmartlabs/concord/blob/97fbce21b7f6843b5048e96d481b0ec9a1dba713/dependency-manager/src/main/java/com/walmartlabs/concord/dependencymanager/DependencyManager.java#L300

**Comment by ibodrov** [comment]
This particular failure can be a transient error, i.e. when Aether tries several repositories before it succeeds or fails. It cannot be used to decide whether the download was successful or not.

**Comment by ibodrov** [comment]
Closing this for now.
