### ISSUE TITLE
Improve warning if plugin may be incompatible

### ISSUE THREAD

**Issue by codyaverett** [walmartlabs/concord#270]
We are using concord 1.70.1 release with the `concord-v2` runtime and tried using a newer version of the ansible plugin (1.72.0) which isn't 100% compatible with the 1.70.1 runtime.

The ansible plugin still applied the playbook to our server before the error was thrown and it was not apparent to us that the plugin version we chose was not supported by the runtime.  Thus it would be useful for a plugin to be able to specify a minimum runtime and alert us if that minimum requirement is not met.

e.g.
```yaml
# custom flow, calls the ansible task with some default params
  - call: ansible-playbook  
     in:
       playbook: deploy
       extraVars:
         projectName: ${projectName}
         version: ${version}
     error:
       # False negatives would be caught here
       - log: ${lastError}
```

```java
12:37:41 [INFO ] Dependencies: 
	mvn://com.walmartlabs.concord.plugins.basic:concord-tasks:1.70.1
	mvn://com.walmartlabs.concord.plugins.basic:slack-tasks:1.70.1
	mvn://com.walmartlabs.concord.plugins.basic:http-tasks:1.70.1
	mvn://com.walmartlabs.concord.plugins.basic:ansible-tasks:1.72.0
12:37:47 [INFO ] Process status: RUNNING
12:37:54 [WARN ] java.lang.RuntimeException: java.lang.NoSuchMethodError: com.walmartlabs.concord.runtime.v2.sdk.TaskResult.of(Z)Lcom/walmartlabs/concord/runtime/v2/sdk/TaskResult$SimpleResult;
12:37:54 [WARN ] 	at com.walmartlabs.concord.runtime.v2.runner.logging.SegmentedLogger.executeInThreadGroup(SegmentedLogger.java:113)
```

**Comment by ibodrov** [comment]
@codyaverett thanks for the report! We found the culprit yesterday https://github.com/walmartlabs/concord/issues/266
I'm going to close this issue in favor of #266, please watch it for the progress.

**Comment by codyaverett** [comment]
Excellent! Eagerly awaiting the fix! 🙂
Thanks @ibodrov

**Comment by ibodrov** [comment]
We might end up doing (basically) nothing about it. :-(
Users of ansible-tasks `1.49.0` to `1.70.1` would have to update to `1.71.0` or higher.
Even if we "fix" the code, it would still require a new release.
I believe this https://github.com/walmartlabs/concord/pull/267 will be able to help with "forcing" the upgrade.

We have a test that verifies whether an older version of Concord Agent can work with the new version of Concord Server. I believe, it's time we start testing older versions of plugins too.
