### ISSUE TITLE
SecretsManager needs a createOrUpdate method

### ISSUE THREAD

**Issue by Randgalt** [walmartlabs/concord#30]
We're currently using `SecretManager.createBinaryData` - what we really need is `SecretManager.createOrUpdateBinaryData`. We're using SecretManager as a secure storage mechanism only so key recovery isn't an issue. We want to be able to set a secret referenced by name whether it exists or not.

**Comment by ibodrov** [comment]
I'm probably going to refactor it later: `SecretManager` shouldn't expose the type of the DB operation but rather a set of high-level methods to do the same.
Expect breakage :-)
