### ISSUE TITLE
Concord proccess fails to run docker container- error during connect 

### ISSUE THREAD

**Issue by megamattzilla** [walmartlabs/concord#398]
Concord processes that trys to run a docker containers always fail with error:
```
error during connect: Post http://dind:2375/v1.24/images/create?fromImage=alpine&tag=latest: dial tcp: lookup dind on 127.0.0.11:53: no such host
```

Concord file is using the provided [docker example](https://concord.walmartlabs.com/docs/plugins/docker.html#usage)
```yaml
flows:
  default:
    - docker: library/alpine
      cmd: echo '${greeting}'

configuration:
  arguments:
    greeting: "Hello, world!"
``` 

I first noticed this behavior trying to run [custom ansible docker images](https://concord.walmartlabs.com/docs/plugins/ansible.html#custom-docker-images) but have been able to repro the same error with simple docker tasks. 

Concord is installed using the provided [docker-compose step](https://concord.walmartlabs.com/docs/getting-started/install/docker-compose.html).

I have experienced the same error on multiple different Linux virtual machines running latest concord server version.

Ubuntu 20.04
Docker version 20.10.5, build 55c4c88
docker-compose version 1.28.6, build 5db8d86f

also tested with:
Docker version 19.03.8, build afacb8b7f0
docker-compose version 1.29.1, build c34c88b2

Full Proccess Log
```23:10:45 [INFO ] Downloading the process state...
23:10:45 [INFO ] Process state download took 17ms
23:10:45 [INFO ] Runtime: concord-v1
23:10:45 [INFO ] Resolving process dependencies...
23:10:45 [INFO ] Dependencies: 
	mvn://com.walmartlabs.concord.plugins.basic:concord-tasks:1.84.0
	mvn://com.walmartlabs.concord.plugins.basic:slack-tasks:1.84.0
	mvn://com.walmartlabs.concord.plugins.basic:http-tasks:1.84.0
23:10:49 [INFO ] Process status: RUNNING
23:10:50 DOCKER: Using default tag: latest
23:10:50 DOCKER: error during connect: Post http://dind:2375/v1.24/images/create?fromImage=alpine&tag=latest: dial tcp: lookup dind on 127.0.0.11:53: no such host
23:10:50 [WARN ] call ['library/alpine', 'echo 'Hello, world!'', '/tmp/concord-agent/workDirs/dce8c137-c194-4dc3-a4d8-d092a170dbcf'] -> finished with code 1
23:10:50 [ERROR] main -> unhandled exception
java.lang.RuntimeException: Docker process finished with with exit code 1
	at com.walmartlabs.concord.plugins.docker.DockerTask.execute(DockerTask.java:108)
	at com.walmartlabs.concord.runner.TaskCallInterceptor.invoke(TaskCallInterceptor.java:64)
	at com.walmartlabs.concord.runner.engine.EngineFactory$JavaDelegateHandlerImpl.execute(EngineFactory.java:215)
	at io.takari.bpm.reducers.ExpressionsReducer$DelegateFn.call(ExpressionsReducer.java:131)
	at io.takari.bpm.reducers.ExpressionsReducer$DelegateFn.call(ExpressionsReducer.java:1)
	at io.takari.bpm.reducers.ExpressionsReducer.reduce(ExpressionsReducer.java:66)
	at io.takari.bpm.reducers.CombiningReducer.reduce(CombiningReducer.java:18)
	at io.takari.bpm.DefaultExecutor.eval(DefaultExecutor.java:61)
	at io.takari.bpm.AbstractEngine.runLockSafe(AbstractEngine.java:209)
	at io.takari.bpm.AbstractEngine.start(AbstractEngine.java:69)
	at com.walmartlabs.concord.runner.Main.start(Main.java:281)
	at com.walmartlabs.concord.runner.Main.executeProcess(Main.java:170)
	at com.walmartlabs.concord.runner.Main.run(Main.java:142)
	at com.walmartlabs.concord.runner.Main.main(Main.java:495)
23:10:51 [ERROR] Process exit code: 1
23:10:51 [INFO ] Process status: FAILED
```

**Comment by megamattzilla** [comment]
I can also replicate this issue on CentOS:  

CentOS Linux release 8.3.2011
Docker version 20.10.6, build 370c289
docker-compose version 1.29.1, build c34c88b2

**Comment by benbroadaway** [comment]
It's because the dind container and the agent container aren't talking. Try a compose config like below. It adds two things
1. Tells the agent to use a remote docker daemon
2. Mounts the same directory for the agent and dind containers' `/tmp` directory

```yaml
version: "3.7"
services:
  concord-db:
    image: "library/postgres:10.4-alpine"
    environment:
      POSTGRES_PASSWORD: "q1q1q1q1"
  concord-server:
    image: "walmartlabs/concord-server"
    depends_on:
      - "concord-db"
    ports:
      - "8001:8001"
    volumes:
      - "./concord.conf:/concord.conf:ro"
    environment:
      CONCORD_CFG_FILE: "/concord.conf"
  concord-dind:
    image: "docker:stable-dind"
    privileged: true
    volumes:
      - "/tmp:/tmp". # mount same directory as agent's tmp volume
    command: "dockerd -H tcp://0.0.0.0:6666 --bip=10.11.13.1/24"
  concord-agent:
    image: "walmartlabs/concord-agent"
    depends_on:
      - "concord-server"
      - "concord-dind"
    environment:
      CONCORD_CFG_FILE: "/concord.conf"
      CONCORD_DOCKER_LOCAL_MODE: "false"
      DOCKER_HOST: tcp://concord-dind:6666  # connect to dind container for docker daemon
    volumes:
      - "./concord.conf:/concord.conf:ro"
      - "/tmp:/tmp"  # mount same directory as dind tmp volume
```

**Comment by megamattzilla** [comment]
Thanks @benbroadaway for the help! 

Adding those lines to the docker-compose.yml file resolved the issue running docker containers in the concord processes. 

For concord newbies like me, these two line additions would be great to include in the default docker-compose.yml file definitions or make a note of it in the quickstart guide. Thanks for getting a PR opened for this as well.

**Comment by benbroadaway** [comment]
It was probably overlooked because newbies _tend_ to not jump directly to running docker containers in their demo environment. There are other limitations to the Docker Compose setup that a fully set up environment can provide (e.g. multiple agent flavors). But Docker should work. Thanks for bringing the issue to our attention 👍
