### ISSUE TITLE
How can I create a admin user

### ISSUE THREAD

**Issue by bimalvasan** [walmartlabs/concord#4]
I'm able to set up all the components in by laptop but unable to have an admin user. Is there any documentation on this?

**Comment by ibodrov** [comment]
When the server starts for the first time, it creates an admin API key https://github.com/walmartlabs/concord/blob/master/server/db/src/main/resources/com/walmartlabs/concord/server/db/v0.0.1.xml#L140 - `auBy4eDWrKWsyhiDp3AQiw`
The key can be used to create more users using the API or to login into the UI: http://localhost:8080/#/login?useApiKey=true

**Comment by bimalvasan** [comment]
Able to login to UI with the key but not allowing to create user or org. When I try to create user using the endpoint *api/v1/user* it is returning *403* with message *Only admins can do that*. Referring this api doc `https://concord.walmartlabs.com/docs/api/user.html#create-or-update-a-user`
Not sure what is missing and what/how to pass **Authorization** part.
