### ISSUE TITLE
 container agent could not connect to server via websocket

### ISSUE THREAD

**Issue by everimbaq** [walmartlabs/concord#5]
I built docker containers following the doc [https://concord.walmartlabs.com/docs/getting-started/install/docker.html].
Everything works well except the agent. I got  a  "connect to server refused" error.
![image](https://user-images.githubusercontent.com/7394813/60574543-50f9e180-9dac-11e9-97d0-29c346baac2a.png)

I can login to the console and create my project and run， but the agent process did not work as expected. Attach to the agent container, I found config file "/opt/concord/agent/default.conf" is empty, is that right？

**Comment by ibodrov** [comment]
The Docker install docs are slightly outdated.
When starting the Agent using container links the websocket address can be specified via
```
SERVER_WEBSOCKET_URL=ws://server:8001/websocket
```
enviroment variable.

Also, the `default.conf` file is just a placeholder used in the Agent's Docker image.
The base configuration is loaded from the classpath. By default the Agent tries to connect to `ws://localhost:8001/websocket` https://github.com/walmartlabs/concord/blob/master/agent/src/main/resources/concord-agent.conf#L51-L53 but if containers links are used it must be overriden.

I'll open a ticket to update the docs.

**Comment by everimbaq** [comment]
> The Docker install docs are slightly outdated.
> When starting the Agent using container links the websocket address can be specified via
> 
> ```
> SERVER_WEBSOCKET_URL=ws://server:8001/websocket
> ```
> 
> enviroment variable.
> 
> Also, the `default.conf` file is just a placeholder used in the Agent's Docker image.
> The base configuration is loaded from the classpath. By default the Agent tries to connect to `ws://localhost:8001/websocket` https://github.com/walmartlabs/concord/blob/master/agent/src/main/resources/concord-agent.conf#L51-L53 but if containers links are used it must be overriden.
> 
> I'll open a ticket to update the docs.

Setting enviroment variable solved my problem, Thanks.
 ```
 SERVER_WEBSOCKET_URL=ws://server:8001/websocket
 ```
