### ISSUE TITLE
How about the scalability and avaliablity of the system?

### ISSUE THREAD

**Issue by everimbaq** [walmartlabs/concord#7]
After serveral days of research and test, We feel concord is great. We are considering to use it in production for automatic CI&CD. I have a few questions so I‘d like to ask， thanks.

1. Is server and agent scalable and high avaliable？
2. I have intermediate data to persistent store and query，（fox exmaple: the deploy history of an app or the build image url),  is concord plugin a good way to achive that?
3. Thannks again for any more tips of using concord.

**Comment by mosabua** [comment]
1. Have you seen the overview deck? We (Walmart) scale Concord to extremely high levels e.g. sometimes hitting 300k endpoints with Ansible in 24h. It scales horizontally with the agents. And you can deploy it in a highly available as well. 

https://concord.walmartlabs.com/training/concord-overview.html#/

2. For simple stuff you can use the KV task. For more complex things the inventory system.

3. Please check out the website for more info as well as the examples in the codebase.

https://concord.walmartlabs.com/overview/index.html
https://concord.walmartlabs.com/docs/index.html
https://github.com/walmartlabs/concord/tree/master/examples

**Comment by everimbaq** [comment]
Yeah, I had read most of the docs, it's detailed and well written. I am running well with the doc‘s help.

However, we are considering to use it to reconstruct our devops totally, including complex processes with thousands of projects and machines. As information about concord is not so much, So I am a little "inexperienced" on how to design and organize a big project with concord . I think it would be great help for developers if there are more complex examples or cases in production.

**Comment by ibodrov** [comment]
We definitely need to describe the production deployment of Concord.
In Walmart we use a HA setup with a "blue-green" style of deployment to avoid downtimes and allow user processes to continue while we upgrading the system.
