### ISSUE TITLE
RFC: Generate JSONSchema for YAML DSL

### ISSUE THREAD

**Issue by cdaringe** [walmartlabs/concord#814]
# Problem

I'm editing away in my concord.yml, but...

- have to reference the DSL reference regularly
- am not always certain that my stringy values match expected enum values
- would like to have intellisense

# Discussion

JSONSchema can often be generated from well-known datamodels. This repo could _emit_ a JSONSchema for `concord.yml`.

Popular/common editors support JSONSchema references and many support it implicitly for well known files and schemas. For example, I can open up a `package.json` in most editors and get intellisense and implicit checking. 

Can we generate and publish JSONSchema to...

- this repo, or
- https://www.schemastore.org/json/

It would be a nice DevUX improvement for all concord users!

From schemastore.org on supported editors:

<img width="808" alt="image" src="https://github.com/walmartlabs/concord/assets/1003261/bb3de7d3-862d-460c-a899-a9a27c3d2757">

**Comment by brig** [comment]
json schema: 
https://repo1.maven.org/maven2/com/walmartlabs/concord/runtime/v2/concord-runtime-model-v2/1.103.1/concord-runtime-model-v2-1.103.1-schema.json

concrd intellij idea plugin: 
https://plugins.jetbrains.com/plugin/20365-concord

**Comment by cdaringe** [comment]
awesome!
