### ISSUE TITLE
Can Generic Trigger response return instanceId? 

### ISSUE THREAD

**Issue by megamattzilla** [walmartlabs/concord#964]
Hello! 

I'm testing a use-case integrating a 3rd party API call to start a concord process. My concord version is 2.15.0. 

I'm using a generic trigger v2 in concord.yml:
```yaml
triggers:
- declare:
    version: 2
    entryPoint: trigger_as3
    conditions:
      class: "AS3"
```

When I send a POST to start the process, it works as expected. 

I would like to be able to query the concord API (from the 3rd party system) to ensure the process was successful, however its not clear what the instanceId for the resulting process was. 

When the trigger is activated, I'm not seeing a instanceId returned by concord:
```bash
# curl -v -H "Authorization: $token"  -H 'Content-Type: application/json' -d '{"myVar": "abc", "class": "AS3"}' http://concord:80/api/v1/events/declare

* Host concord:80 was resolved.
* Connected to concord (xx.xx.xx.xx port 80
> POST /api/v1/events/declare HTTP/1.1
> Host: concord:80
> User-Agent: curl/8.7.1
> Accept: */*
> Authorization: REDACTED
> Content-Type: application/json
> Content-Length: 32
>
* upload completely sent off: 32 bytes

< HTTP/1.1 200 OK
< Server: Jetty(12.0.7)
< Date: Thu, 29 Aug 2024 14:42:54 GMT
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: *
< Access-Control-Allow-Headers: Authorization, Content-Type, Range, Cookie, Origin
< Access-Control-Expose-Headers: cache-control,content-language,expires,last-modified,content-range,content-length,accept-ranges
< Cache-Control: no-cache, no-store, must-revalidate
< Pragma: no-cache
< Expires: 0
< Content-Length: 0
<
```

Is there a way configure my trigger to return a instanceId in the HTTP response? 

Note:
I found that starting a process via the process API does return an instanceId. 

I like the simplicity of the trigger and its preferable for my use-case to just send the necessary JSON the process uses as inputs as application/json. If there was a similar way to start a process via simple POST with JSON body I would switch to that instead.

**Comment by benbroadaway** [comment]
Generic events should not be considered an easier-to-use substitute for the Process API. While both _may_ start a process instance, they are very different mechanisms and generic events have big security implications.

A single generic event may start zero or many processes, across all organizations--any repository definition with a matching `trigger` definition will generate a process instance from the event. That should be a reminder to not put sensitive information in a generic event, and only use generic events when actually appropriate. Further, the API user which sends the event may not have RBAC permission to know about the process(es) it triggered (e.g. it's in a private project).

**Comment by megamattzilla** [comment]
Thanks for the feedback!

The process API is more robust than triggers, I would rather use the process API. 

According to the [process API documentation](https://concord.walmartlabs.com/docs/api/process.html#start-a-process) I found the `/api/v1/process` endpoint only supports content-type multipart/form-data, is that right? 

I am checking with the third party API team I'm working with if they can generate multipart form data. Today they are generating application/json which steered me to using triggers.

For grins, I tried sending application/json to process API, but it reported unsupported media type.  
```
curl -v -H "Authorization: $token" -H 'Content-Type: application/json' -d '{"org": "Default", "project": "project_name", "repo": "repo_name"}'  http://concord:80/api/v1/process

* Connected to concord() port 80
> POST /api/v1/process HTTP/1.1
> Host: concord:80
> User-Agent: curl/8.7.1
> Accept: */*
> Authorization: REDACTED
> Content-Type: application/json
> Content-Length: 70
>
* upload completely sent off: 70 bytes
< HTTP/1.1 415 Unsupported Media Type
< Server: Jetty(12.0.7)
< Date: Thu, 29 Aug 2024 18:14:29 GMT
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: *
< Access-Control-Allow-Headers: Authorization, Content-Type, Range, Cookie, Origin
< Access-Control-Expose-Headers: cache-control,content-language,expires,last-modified,content-range,content-length,accept-ranges
< Cache-Control: no-cache, no-store, must-revalidate
< Pragma: no-cache
< Expires: 0
< Content-Length: 0
< 
```

**Comment by benbroadaway** [comment]
> According to the [process API documentation](https://concord.walmartlabs.com/docs/api/process.html#start-a-process) I found the /api/v1/process endpoint only supports content-type multipart/form-data, is that right?

Not quite right. There's a dumbed-down version for [`GET` requests](https://concord.walmart.com/docs/api/process.html#browser-link). It's intended to allow starting a process from a browser link (i.e. no body) but works from any client.

**Comment by megamattzilla** [comment]
Our use-case requires a request body to provide inputs to concord.  I will see if we can go the route of using process API with multipart form data. 

Thanks for the help, I appreciate it!!

**Comment by benbroadaway** [comment]
FWIW, you _can_ provide inputs through the `GET` API. They just need to be given as url parameters e.g. 

```
/api/v1/org/MyOrg/project/MyProject/repo/MyRepo/start/default?arguments.x=123&arguments.y=boo
                                                                        ^               ^
```
```yaml
flows:
  - log: "x == ${x}" # 123
  - log: "y == ${y}" # boo
````

**Comment by megamattzilla** [comment]
Oh, thats neat! 

I will test that option as well. 

Thanks!!
